Problems copy `FORMULA_MACROFILE`
When having a formula macrofile we get warnings like:
```
error: could not copy file .../html/mymacro.sty to mymacro.sty
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
error: could not copy file .../html/mymacro.sty to mymacro.sty
error: Problems running latex. Check your installation or look for typos in _formulas_dark.tex and check _formulas_dark.log!
```
due to the fact that already a change of directory to the output directory took place.