Protect counter with mutex (regression)
I checked PR #11902 and found a small problem when `DOT_CLEANUP=YES` as I get the warnings:
```
.../aa.c:17: error: Problems running dot: exit code=2, command='dot.exe', arguments='".../doc/html/inline_dotgraph_4b689ea5cd4847e4f5ac9ff55d29fff0.dot" -Tcmapx -o ".../doc/html/dot_inline_dotgraph_4b689ea5cd4847e4f5ac9ff55d29fff0.map"'
Failed to open input file '.../doc/html/inline_mscgraph_7c6951245abdf3122b13597d42cd76cb.msc'
.../bb.c:15: error: Problems generating msc output (error=FILE ERROR). Look for typos in you msc file '.../doc/html/inline_mscgraph_7c6951245abdf3122b13597d42cd76cb.msc'
```

Delayed deletion of files until all code has been written.