Error running test 120 without `--xml`
When testing the doxygen test 120 but without that `--xml` or `--xmlxsd` has been specified we get the error like:
```
error: cannot open tag file .../testing/test_output_120/out/tagfile for writing
```
due to the fact that in this case the `out` directory has not bee created.

Furthermore there were still a number of references to test `116` (the initial number of the test)