Fix variable name collision with clang mingw
This changes the variable name from 'stat' to 'isStatic'.
Otherwise the 'stat' name come into conflict with 'stat'
macro in mingw-w64 headers. This fixes the following error:

commentscan.l:3074:21: error: no member named '_stat64' in 'Entry'
  yyextra->current->stat = TRUE;
  ~~~~~~~~~~~~~~~~  ^

The 'stat' macro is defined in sys/stat.h file in mingw-w64
like this '#define stat _stat64'