Better warning in case of an internal error of a layout element
Better warning in case of an internal error. At the moment we could get warnings like:
```
error: Internal inconsistency: member 10 should not be part of LayoutDocManager::Namespace entry list
```
though it would be better to have a mnemonic instead of a number.