Doxygen stops on invalid namespace name
When we have a problem like:
```
/**
 * of @namespace.
 *
 * Only one
 */
void tracker_namespace_manager_add_prefix () {}
```

on windows we get the message:
```
error: Could not open file .../html/namespace

_only.html for writing
```
and doxygen will terminate (due to `\n` in the file name to be generated).