Detection of missing / superfluous `\n` in warnings
Prevent:
```
warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
```
for the GNU compiler we need the `##` as otherwise we get the errors like:
```
/message.h:104:35: error: expected primary-expression before ‘)’ token
  104 |    warn_(file,line,fmt,__VA_ARGS__); \
      |                                   ^
```