Fix conversion of ghc::filesystem::path to std::string
This fixes the following compiler error with clang

portable.cpp:652:10: error: no matching constructor for initialization of 'std::ofstream' (aka 'basic_ofstream<char>')
  return std::ofstream(fs::path(fileName.str()), mode);
         ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This happens because std::ifstream does not have any constructor
with ghc::filesystem::path, instead with filesystem::path.