Better warning in case of error in dot / msc / dia image
The warning messages regarding dot / msc / dia are a bit cryptic and it is hard to find where the file is invoked.
The current messages look like:
```
Error detected at line 5: Unknown source entity 'fail1'.
Input format error for '.../html/inline_mscgraph_1.msc'
error: Problems generating msc output (error=INPUT FORMAT ERROR). Look for typos in you msc file .../html/inline_mscgraph_1.msc

Error detected at line 5: Unknown source entity 'fail1'.
Input format error for '.../aa.msc'
error: Problems generating msc output (error=INPUT FORMAT ERROR). Look for typos in you msc file .../aa.msc

error: Problems running dot: exit code=1, command='dot', arguments='".../html/inline_dotgraph_1.dot" -Tpng -o ".../html/inline_dotgraph_1.dot.png"'
error: Problems running dot: exit code=1, command='dot', arguments='".../aa.dot" -Tpng -o ".../html/aa.dot.png"'

error: Problems running D:\Programs\dia\0.97.2\bin\dia.exe. Check your installation or look typos in you dia file .../aa.dia
```

Better it is to have the source file and line in front of it, like most warnings / errors, so it might be easier to locate the problem.

Based on the comment https://github.com/doxygen/doxygen/pull/642#issuecomment-731133017 in #642.