Incorrect warning due to import statement
With the Objective C example:
**aa.m**
```
#import "bb.h"
```

**bb.h**
```
#ifndef INCLUDED_OOFUNCTIONATTRIBUTES_h
#endif
```
we get the warning:
```
bb.h:2: Error: More #endif's than #if's found.
```
as the first line of the imported file is read as "comment", by delaying the read this is prevented.