Compilation error Windows (cannot allocate an array of constant size 0)
On windows with Visual Studio 2013 the following error is given (3 times):
Error    14    error C2466: cannot allocate an array of constant size 0    ...\generated_src\resources.cpp    28198    1    _doxygen
In this patch the size of the array declaration for windows is set to 1 in case there are no elements