CMakeLists.txt: use 64-bit file API on 32-bit linux
Without the change `doxygen` fails to run when built against
`i686-linux` target and installed on thew filesystem with 64-bit
inodes (`btrfs` with many files in my case):

    $ doxygen -g && doxygen && echo ok
    Configuration file 'Doxyfile' created.
    ...
    error: Doxyfile not found and no input file specified!

This happens because the inode number is outside 32-bit values:

    $ stat Doxyfile
    ...
    Device: 0,31    Inode: 11833552292  Links: 1

After the change the doc generation succeeds as expected:

    $ doxygen -g && doxygen && echo ok
    ...
    ok

The change enables the respective macros to enable 64-bit API.