No warning for incorrect ALIASES
When having the alias:
```
"\latexonly mytable=\\mytable \endlatexonly"
```
the 1.9.1. version gave a warning:
```
error: Illegal ALIASES format '\latexonly mytable=\\mytable \endlatexonly'. Use "name=value" or "name{n}=value", where n is the number of arguments
```
though the current version doesn't give a warning, probably due to the regexp replacement. Now most likely the string found starts at `mytable=`
The alias should start at the beginning of the string when searching.