Building Cygwin version of doxygen fails
The ghc filesystem does not support, resulting in:
```
.../src/filesystem.hpp:76:2: error: #error "Operating system currently not supported!
   76 | #error "Operating system currently not supported!"
      |  ^~~~~
```

Added Cygwin in selection of supported "GHC_OS_DETECTED".