Incorrect python 3.7.5 string
Regression on:
```
Refactoring: use more modern print(f"") style prints in configgen.py for formatting
```
with python 3.7.5 we got an error like:
```
  File ".../src/configgen.py", line 528
    print(f"    {{ {'\"'+name+'\",':<26} Info{{ {'Info::'+map[type]+',':<13} &ConfigValues::m_{name+',':<23} {mappingStr}}}}},")
         ^
SyntaxError: f-string expression part cannot include a backslash
NMAKE : fatal error U1077: 'D:\Programs\Python\Python37\python.exe' : return code '0x1'
```