Warnings when generating diagrams with LaTeX and HTMLHelp / QHP enabled
When we have an example with dot / msc /plantuml / class / call graph we and we have LaTeX enabled an chm and / or qhp we get warnings when we generate the chm / qch file.
The warnings are (for chm) like:
```
HHC5003: Error: Compilation failed while compiling inline_mscgraph_1.eps.
HHC5003: Error: Compilation failed while compiling msc_tst.eps.
HHC5003: Error: Compilation failed while compiling inline_mscgraph_1.msc.png.
HHC5003: Error: Compilation failed while compiling tst.msc.png.
HHC5003: Error: Compilation failed while compiling classcls1__inherit__graph.pdf.
HHC5003: Error: Compilation failed while compiling classcls1_a50c27321727c278dc467aa3d909a2dc1_icgraph.pdf.
HHC5003: Error: Compilation failed while compiling classcls2__coll__graph.pdf.
HHC5003: Error: Compilation failed while compiling classcls2__inherit__graph.pdf.
HHC5003: Error: Compilation failed while compiling classcls2_a963159bbf5424f67f740056941f9c667_cgraph.pdf.
HHC5003: Error: Compilation failed while compiling inline_dotgraph_1.dot.png.
HHC5003: Error: Compilation failed while compiling inline_umlgraph_2.eps.
HHC5003: Error: Compilation failed while compiling inline_umlgraph_3.png.
HHC5003: Error: Compilation failed while compiling tsts.dot.png.

The following files were not compiled:
inline_mscgraph_1.eps
msc_tst.eps
inline_mscgraph_1.msc.png
tst.msc.png
classcls1__inherit__graph.pdf
classcls1_a50c27321727c278dc467aa3d909a2dc1_icgraph.pdf
classcls2__coll__graph.pdf
classcls2__inherit__graph.pdf
classcls2_a963159bbf5424f67f740056941f9c667_cgraph.pdf
inline_dotgraph_1.dot.png
inline_umlgraph_2.eps
inline_umlgraph_3.png
tsts.dot.png
```
as these files come from the LaTeX / RTF generation. (Analogous messages for the gch generation)
the used `Doxygen::indexList` is only for HTML like output, so the LaTeX etc output files should not be added.