Unknown configuration enum values
In case we set for instance `DOT_IMAGE_FORMAT       = SVG` (and generate call graphs) we get messages from the `dot` tool like:
```
error: Problems running dot: exit code=1, command='dot', arguments='".../example/html/test_8cpp_a764ac60c654173eb1a0afd0906ad5a12_icgraph.dot" -TSVG -o ".../example/html/test_8cpp_a764ac60c654173eb1a0afd0906ad5a12_icgraph.SVG"'
```
on other places (e.g `HTML_FORMULA_FORMAT`) and an unknown or enum value with a wrong case, the default value is (silently) taken.

We now check:
- is the enum value of the correct case otherwise (silently) set it to the correct case.
- in case of an unknown enum value a warning is given and the default value is used