Revert "Fix conversion of ghc::filesystem::path to std::string"
This reverts commit 289e76aa67646b4fc59cb2a8e713b03893917afd.

That commit shows compiler error with mingw gcc as following:
portable.cpp:653:64: error: no matching function for call to 'std::basic_ofstream<char>::basic_ofstream(std::wstring, std::ios_base::openmode&)'
  653 |   return std::ofstream(fs::path(fileName.str()).wstring(), mode);
      |                                                                ^