Making tests valid for python 3
Test 65 gave some problems with python3:
```
Traceback (most recent call last):
  File "D:/Programs/Doxygen/Doxygen-.git/doxygen/testing/runtests.py", line 487, in <module>
    main()
  File "D:/Programs/Doxygen/Doxygen-.git/doxygen/testing/runtests.py", line 484, in main
    sys.exit(testManager.perform_tests())
  File "D:/Programs/Doxygen/Doxygen-.git/doxygen/testing/runtests.py", line 388, in perform_tests
    tester = Tester(self.args,test)
  File "D:/Programs/Doxygen/Doxygen-.git/doxygen/testing/runtests.py", line 13, in __init__
    self.config    = self.get_config()
  File "D:/Programs/Doxygen/Doxygen-.git/doxygen/testing/runtests.py", line 71, in get_config
    for line in f.readlines():
  File "D:\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 236: character maps to <undefined>
```
this happened on multiple places and also with the `popen` command.

Created, analogous to `doc/translator.py`, special open functions so that the code works for Python 2 and Python 3.