Typeerror when running tests
Some tests get (#8313):
```
  File "/home/runner/work/doxygen/doxygen/testing/runtests.py", line 55, in clean_header
    rtnmsg+=0
TypeError: can only concatenate str (not "int") to str
```
most likely caused by the fact that `more` has error lines and that here not `0` (zero) but  `o` should be used for the concatenation.